#!/bin/bash

number_of_commits=$(git rev-list HEAD --count)
git_release_version=$(git describe --tags --always --abbrev=0)

sed -i.bak -e "1s/^/[$git_release_version (build #$number_of_commits)] /" $1
